[package]
name = "EzRustScan"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
ipnetwork = "0.20.0"
colored = "2.2.0"
indicatif = "0.17.9 "

[dependencies.clap]
version = "4.5.23"
features = ["derive"]